export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST'
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS'
export const GET_USER_POSTS_FAIL = 'GET_USER_POSTS_FAIL'
export const GET_USER_POSTS_LIKES = 'GET_USER_POSTS_LIKES'

export const GET_USER_POSTS_PROFILE_REQUEST = 'GET_USER_POSTS_PROFILE_REQUEST'
export const GET_USER_POSTS_PROFILE_SUCCESS = 'GET_USER_POSTS_PROFILE_SUCCESS'
export const GET_USER_POSTS_PROFILE_FAIL = 'GET_USER_POSTS_PROFILE_FAIL'
export const GET_USER_POSTS_PROFILE_LIKES = 'GET_USER_POSTS_PROFILE_LIKES'

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'

export const GET_USER_FOLLOWING_REQUEST = 'GET_USER_FOLLOWING_REQUEST'
export const GET_USER_FOLLOWING_SUCCESS = 'GET_USER_FOLLOWING_SUCCESS'
export const GET_USER_FOLLOWING_FAIL = 'GET_USER_FOLLOWING_FAIL'

export const GET_USER_FOLLOWING_POST_REQUEST = 'GET_USER_FOLLOWING_POST_REQUEST'
export const GET_USER_FOLLOWING_POST_SUCCESS = 'GET_USER_FOLLOWING_POST_SUCCESS'
export const GET_USER_FOLLOWING_POST_FAIL = 'GET_USER_FOLLOWING_POST_FAIL'

export const GET_USER_FOLLOWING_LIKE_REQUEST = 'GET_USER_FOLLOWING_LIKE_REQUEST'
export const GET_USER_FOLLOWING_LIKE_SUCCESS = 'GET_USER_FOLLOWING_LIKE_SUCCESS'
export const GET_USER_FOLLOWING_LIKE_FAIL = 'GET_USER_FOLLOWING_LIKE_FAIL'

export const FOREIGN_USER_PROFILE_REQUEST = 'FOREIGN_USER_PROFILE_REQUEST'
export const FOREIGN_USER_PROFILE_SUCCESS = 'FOREIGN_USER_PROFILE_SUCCESS'
export const FOREIGN_USER_PROFILE_FAIL = 'FOREIGN_USER_PROFILE_FAIL'
export const FOREIGN_POST_PROFILE_SUCCESS = 'FOREIGN_POST_PROFILE_SUCCESS'