export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST'
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS'
export const GET_USER_POSTS_FAIL = 'GET_USER_POSTS_FAIL'
export const GET_USER_POSTS_LIKES = 'GET_USER_POSTS_LIKES'

export const GET_USER_POSTS_PROFILE_REQUEST = 'GET_USER_POSTS_PROFILE_REQUEST'
export const GET_USER_POSTS_PROFILE_SUCCESS = 'GET_USER_POSTS_PROFILE_SUCCESS'
export const GET_USER_POSTS_PROFILE_FAIL = 'GET_USER_POSTS_PROFILE_FAIL'
export const GET_USER_POSTS_PROFILE_LIKES = 'GET_USER_POSTS_PROFILE_LIKES'

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'

export const POST = 'POST'
